# Population size
population_size: 100

# Number of generations
num_generations: 25000

# Path to the image to be approximated
target_img_path: './input/contest/at_the_hockey.jpg'

# Output folder name for this target image
target_img_alias: 'At the hockey'

# Path to the output folder directory for all target images
output_dir: './output/contest'

# Path to the directory with letters which are used for approximation
letters_dir: './letters/contest/at_the_hockey'

# Number of the samples to save (1 sample - 1 generation)
samples_to_save: 500
